name: indent html action emacs moi

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Run a one-line script
      run: |
        echo "Hello from indent html action emacs moi"
        echo "poub generaed" ; 
        #poubActionGenerated.txt
      
#TODO if https://www.youtube.com/watch?v=eB0nUzAI7M8&ab_channel=Fireship


 #gjhkhkhjh
 
