name: indent html action emacs moi

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Run a one-line script
      run: echo Hello from Octo Organization




//docker run 
//-v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site 
//jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
