name: indent html action emacs moi

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Run a one-line script
      run: |
        echo "Hello from indent html action emacs moi"
        echo "Action generating" ; 
        #file creation :
        echo "poub generated" > poubActionGenerated.txt
        #commit -m "Action commit moi"
      
    #from https://github.com/marketplace/actions/add-commit   
    - name: Commit changes
      uses: EndBug/add-and-commit@v5
      with:
        author_name: Your Name
        author_email: mail@example.com
        message: "Your commit message"
        add: "*.html"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
#TODO if https://www.youtube.com/watch?v=eB0nUzAI7M8&ab_channel=Fireship


 #gjhkhkhjh
 
